### ISSUE TITLE
 templateContent async not working in v2.1.0

### ISSUE THREAD

**Issue by beckend** [ampedandwired/html-webpack-plugin#153]
webpack.config.js(es6 babel) and shortened html string:
```
new (require('html-webpack-plugin'))({
  templateContent(templateParams, compilation, cb) {
    cb(null, '<!DOCTYPE html>');
  }
})
```
#### Using webpack v1.12.9, node v5.3.0, yields:
```ERROR in Template execution failed: TypeError: cb is not a function```  

--
#### As for webpack v2.0.2-beta:
```
Child html-webpack-plugin for "index.html":

    ERROR in ./~/html-webpack-plugin/loader.js!./~/html-webpack-plugin/default_index.html
    Module parse failed: /bla/bla/node_modules/html-webpack-plugin/loader.js!/bla/bla/node_modules/html-webpack-plugin/default_index.html 'with' in strict mode (4:0)
    You may need an appropriate loader to handle this file type.
    | obj || (obj = {});
    | var __t, __p = '';
    | with (obj) {
    | __p += '<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="UTF-8">\n    <title>' +
    | ((__t = ( htmlWebpackPlugin.options.title )) == null ? '' : __t) +
```
  
Everything works fine in v1.7.0.

**Comment by jantimon** [comment]
Hi beckend,

that's true - the version 2.0 has a very different approach to render the html.
It uses a webpack child compiler instead of node.

This allows to use the HTML loader or other loaders.
However the `templateContent` function might return a promise:

https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/index.js#L219

**Comment by beckend** [comment]
Okay I got it to work, the new version was quite a ride.
So unto business:

templateContent is currently broken:
* The new plugin tries to execute `self.compileTemplate` with self.options.template at https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/index.js#L49 regardless if you set self.options.template or not.  
So the plugin does not throw an error or do any kind of checks for these 2 different use cases so far(that if you specify both template and templateContent, or just use templateContent).

* This compilation is then resolved or rejected at https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/index.js#L75 and of course will be an unintended error rejected.

And also `templateParams` function does not take parameters anymore! It's an object now:
```
{
  templateParams: {
    webpack: webpackCompilationJson,
    webpackConfig: webpackCompilationOptions,
    htmlWebpackPlugin: {
      files: webpackAssets,
      options: self.options
    }
  }
}
```

Fix should be simple, do you want a PR?

**Comment by jantimon** [comment]
The templateContent is one reason why we switched from 1.x to 2.x.
If you are using templateContent 1.x is faster as it doesn't compile anyway.

For some reason the default_index.html doesn't compile correctly.
If it would it should work.
